export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_FAILED = 'GET_SERVICES_FAILED';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_FAILED = 'CREATE_SERVICE_FAILED';
export const SET_UPDATE_SERVICE = 'SET_UPDATE_SERVICE';
export const HANDLE_UPDATE_SERVICE = 'HANDLE_UPDATE_SERVICE';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_FAILED = 'UPDATE_SERVICE_FAILED';
// Categories
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';
export const CREATE_CATEGORY_FAILED = 'CREATE_CATEGORY_FAILED';
export const SET_UPDATE_CATEGORY = 'SET_UPDATE_CATEGORY';
export const HANDLE_UPDATE_CATEGORY = 'HANDLE_UPDATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';  

export const GROUP_SERVICES = 'GROUP_SERVICES';

// Times
export const GET_TIMES = 'GET_TIMES';
export const GET_TIMES_SUCCESS = 'GET_TIMES_SUCCESS';
export const GET_TIMES_FAILED = 'GET_TIMES_FAILED';

// Shifts
export const ADD_SERVICE_SHIFT = 'ADD_SERVICE_SHIFT';
export const REMOVE_SERVICE_SHIFT = 'REMOVE_SERVICE_SHIFT'; 
export const ADD_NAME_SHIFT =  'ADD_NAME_SHIFT';
export const ADD_DATE_SHIFT = 'ADD_DATE_SHIFT';
export const ADD_TIME_SHIFT = 'ADD_TIME_SHIFT';
export const REMOVE_TIME_SHIFT = 'REMOVE_TIME_SHIFT';

export const CREATE_SHIFT = 'CREATE_SHIFT';
export const CREATE_SHIFT_SUCCESS = 'CREATE_SHIFT_SUCCESS';
export const CREATE_SHIFT_FAILED = 'CREATE_SHIFT_FAILED';

export const GET_SHIFTS_DATE = 'GET_SHIFTS_DATE';
export const GET_SHIFTS_DATE_SUCCESS = 'GET_SHIFTS_DATE_SUCCESS';
export const GET_SHIFTS_DATE_FAILED = 'GET_SHIFTS_DATE_FAILED';

// Login
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

// Autenticación de usuario
export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';

// SHIFTS ADMIN
export const GET_SHIFTS_DATE_ADMIN = 'GET_SHIFTS_DATE_ADMIN';
export const GET_SHIFTS_DATE_ADMIN_SUCCESS = 'GET_SHIFTS_DATE_ADMIN_SUCCESS';
export const GET_SHIFTS_DATE_ADMIN_FAILED = 'GET_SHIFTS_DATE_ADMIN_FAILED';

// SHIFT DONE
export const UPDATE_SHIFT = 'UPDATE_SHIFT';
export const UPDATE_SHIFT_SUCCESS = 'UPDATE_SHIFT_SUCCESS';
export const UPDATE_SHIFT_FAILED = 'UPDATE_SHIFT_FAILED';

// Alertas
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDDEN_ALERT = 'HIDDEN_ALERT';

// DESHABILITAR FECHA
export const DATE_DISABLE = 'DATE_DISABLE';
export const DATE_DISABLE_SUCCESS = 'DATE_DISABLE_SUCCESS';
export const DATE_DISABLE_FAILED = 'DATE_DISABLE_FAILED';
// OBTENER FECHA DESHABILITADAS
export const GET_DATES_DISABLE = 'GET_DATES_DISABLE';
export const GET_DATES_DISABLE_SUCCESS = 'GET_DATES_DISABLE_SUCCESS';
export const GET_DATES_DISABLE_FAILED = 'GET_DATES_DISABLE_FAILED';
// HABILITAR FECHA
export const DATE_ENABLE = 'DATE_ENABLE';
export const DATE_ENABLE_SUCCESS = 'DATE_ENABLE_SUCCESS';
export const DATE_ENABLE_FAILED = 'DATE_ENABLE_FAILED';  

